package com.fseer.dn.dn_cms.entity;

// Generated 2014-6-28 20:23:50 by Hibernate Tools 4.0.0


/**
 * Admin generated by hbm2java
 */
@SuppressWarnings("serial")
public class Admin implements java.io.Serializable {
	
	
	private String loginId;
	private String password;

	public Admin() {
	}

	public Admin(String loginId, String password) {
		this.loginId = loginId;
		this.password = password;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		String str = "用户名:[" + this.loginId + "].密码:[ " + this.password + "]";
		return str;
	}
	
	
}
