package com.fseer.dn.dn_cms.entity;

// Generated 2014-6-28 20:23:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Channel generated by hbm2java
 */
@SuppressWarnings("serial")
public class Channel implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Article> articles = new HashSet<Article>(0);

	public Channel() {
	}

	public Channel(int id) {
		this.id = id;
	}

	public Channel(int id, String name, Set<Article> articles) {
		this.id = id;
		this.name = name;
		this.articles = articles;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
